### ISSUE TITLE
Missing textures of some parts

### ISSUE THREAD

**Issue by Liiw** [SilentChaos512/SuperMultiDrills#11]
Hello!

I have SMD installed on a 1.10.2 Spongeforge server. When looking up the mod items in JEI, all, but the drill head textures seem to be missing. Please see image attached:

![image](https://cloud.githubusercontent.com/assets/14122419/24815717/dd20c5ea-1bde-11e7-96d0-deb0a6908808.png)

EDIT:
Note: This also means, that the handheld tools look like black and purple squares.

**Comment by SilentChaos512** [comment]
What are the exact versions of SMD and Silent Lib you have installed?

**Comment by Liiw** [comment]
Thank you for your reply! The versions are:

SilentLib-1.10.2-2.0.6-52
SuperMultiDrills-1.10.2-1.4.3-30

**Comment by SilentChaos512** [comment]
OK, I just finished updating for Silent Lib 2. In case you're not familiar with it, SL2 allows mods to run on both 1.10 and 1.11. The new build of drills is SuperMultiDrills-1.11.x-1.5.0-33.jar, which I'm uploading now. Keep using the 1.10.2 versions of Silent Lib.

**Comment by SilentChaos512** [comment]
Seems there are still some issues (#12). I will work those out as time allows, I work a lot of hours on weekends.

**Comment by Liiw** [comment]
Hello!

Thank you for your dedicated support on this issue! I will test and let you know as soon as possible. I too have work and other business during weekend times and was unable to do it earlier. It is understandable.

**Comment by Liiw** [comment]
Hello again!

I finally got around to updating the mods on the server and while most of the textures are back, as mentioned, some of the drills were invisible on JEI. I also couldn't craft a random drill from components, but maybe I was doing something wrong. I am attaching an image for confirmation:

![image](https://cloud.githubusercontent.com/assets/14122419/25111620/b9114e22-23f4-11e7-94c1-9db28c1f5381.png)

**Comment by SilentChaos512** [comment]
You seem to be missing a battery in the screenshot. I just tested it and crafting does work. Drills are still invisible in 1.10.2 though and I'm not entirely sure why. There are probably some capital letters sneaking in somewhere.

**Comment by Liiw** [comment]
Oh, my bad. I somehow forgot the apparent need for power storage on a portable electrical device :P
