### ISSUE TITLE
Some drill heads not using proper names + Drills not showing textures

### ISSUE THREAD

**Issue by Espeon1296** [SilentChaos512/SuperMultiDrills#12]
After updating to the latest versions of both SilentLib, SilentsGems and SuperMultiDrills, I've found that not only do some drill heads show improper names, but when crafting a drill, the texture appears blank. The individual parts have the proper sprites, however.

As stated, using SilentLib 2.0.6-52, SilentsGems 2.3.6-159, and SuperMultiDrills 1.5.0-33, on 1.10.2

Here's a couple images.

![image](https://cloud.githubusercontent.com/assets/27133160/24836187/8746f1ce-1cda-11e7-9870-3d506c6e9302.png)
![image](https://cloud.githubusercontent.com/assets/27133160/24836188/8cd25408-1cda-11e7-96a6-904021c70b4b.png)

**Comment by SilentChaos512** [comment]
At a glance it looks like just the heads for the new gems are missing localizations. The original twelve are fine.
Drills are definitely invisible, at least in 1.10 (I think they're OK in 1.11). Something is wrong with the model handler, I guess.
