### ISSUE TITLE
[Bug] Disassembly Kit Deletes Multi-Drill

### ISSUE THREAD

**Issue by Mohron** [SilentChaos512/SuperMultiDrills#13]
SuperMultiDrills-1.11.x-1.5.1-37.jar
forge-1.11.2-13.20.0.2282-universal.jar

[![https://gyazo.com/bb6bb7cb86dfc0270f87fae4d9fcaf8a](https://i.gyazo.com/bb6bb7cb86dfc0270f87fae4d9fcaf8a.gif)](https://gyazo.com/bb6bb7cb86dfc0270f87fae4d9fcaf8a)

**Comment by SilentChaos512** [comment]
I'm getting different behavior (with the disassembly kit being destroyed), but either way the recipe handler is bugged.

**Comment by Mohron** [comment]
It was in a modified vanilla crafting table that holds its inventory if that matters.
RealBench-1.11.2-1.3.2
