### ISSUE TITLE
Game crashes when booting up a world

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/SuperMultiDrills#18]
Silent Gear Version: SilentGear-1.15.2-1.6.0+86
SuperMultiDrills Version: SuperMultiDrills-1.15.2-2.0.0+1
Forge Version: 31.1.46

Whenever I boot up a world, the game crashes, log[ here](https://pastebin.com/mVS0rC4H)

**Comment by SilentChaos512** [comment]
Fixed by 1ec54238f261623460905e2ee95dd1302b0af715, which removed the unused EvalEx expression for now. Version 2.0.1 is available on Curse.
