### ISSUE TITLE
Infinite FE

### ISSUE THREAD

**Issue by Funnymeme1** [SilentChaos512/SuperMultiDrills#19]
## Versions

- **Super Multi-Drills**: 2.0.1
- **Silent Gear**: 1.6.0
- **Silent Lib**: 4.6.0
- **Forge**: 31.1.47
- **Modpack**: Custom 
- **Optifine Installed**: No 

## Expected Behavior

Crafting a drill with upgrades/replacements would keep its FE the same

## Actual Behavior

Whenever you craft a drill with upgrades/replacements, it seems to come out with the same amount of FE as the battery had when you added it.

## Links/Images

- (Link)
- (Another link, if needed)

## Steps to Reproduce the Problem

1.  Make drill
2.  Craft it with something that results with it ending up in the output slot
3.  FE changes to be how full the battery was when it was added.

**Comment by Funnymeme1** [comment]
Wait, this is more confusing. Making a new drill and doing this caused it to go from full to empty.

**Comment by SilentChaos512** [comment]
Should get set to whatever the charge level on the battery was when
crafted. It's because the part's `onAddedToGear` method is being called too
often.

**Comment by SilentChaos512** [comment]
Will be fixed by the next Silent Gear update (1.6.1)
