### ISSUE TITLE
crash during startup: NoClassDefFoundError

### ISSUE THREAD

**Issue by LlubNek** [SilentChaos512/SuperMultiDrills#24]
## Versions

- **Super Multi-Drills**: SuperMultiDrills-1.16.3-2.2.1+6.jar
- **Silent Gear**: SilentGear-1.16.3-2.5.1+206.jar
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63.jar
- **Forge**: 35.1.37
- **Modpack**: N/A 
- **Optifine Installed**: Yes 

## Expected Behavior
Normal startup without errors

## Actual Behavior

Crash with error screen below.

## Links/Images

![image](https://user-images.githubusercontent.com/313762/104853956-3c1f6900-58d2-11eb-8f8c-79959ab95b3e.png)
[latest.log](https://github.com/SilentChaos512/SuperMultiDrills/files/5826678/latest.log)
[crash-2021-01-17_14.32.03-fml.txt](https://github.com/SilentChaos512/SuperMultiDrills/files/5826679/crash-2021-01-17_14.32.03-fml.txt)

## Steps to Reproduce the Problem
1.  install mods
2.  start minecraft
3.  observe error

**Comment by SilentChaos512** [comment]
Already fixed in 2.2.2, please update the mod.

**Comment by LlubNek** [comment]
Sorry, yeah, looks good so far with 2.2.2.  GDLauncher didn't show me the update.
