### ISSUE TITLE
JEI Interface Fails to Display when Connected to Server w/ this mod (tag not bound)

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/SuperMultiDrills#25]
## Versions

- **Super Multi-Drills**: SuperMultiDrills-1.16.3-2.2.2+7
- **Silent Gear**: SilentGear-1.16.3-2.5.2+207 
- **Silent Lib**: SilentLib-1.16.3-4.9.1+64
- **Forge**: 35.1.37
- **Modpack**: N/A 
- **Optifine Installed**: Yes

## Expected Behavior
I expect JEI items display to appear in inventory screen

## Actual Behavior
When connecting to a server with this mod installed, JEI ceases to function. Using the keybind to display JEI screen has no affect.
When playing singleplayer, all works as expected, and, if connecting to a server after having loaded a single player world, it also works as expected.

## Links/Images
This issue compiles most of the relevant information on the subject: https://github.com/mezz/JustEnoughItems/issues/2213

**Comment by SilentChaos512** [comment]
"Tag supermultidrills:drill_batteries used before it was bound"... Of course. That must be it. Really need to figure out which mod triggers that issue and a good way to prevent it.

**Comment by ghost** [comment]
I see. Yeah, someone in the referenced issue said that Apotheosis was doing something wrong with tags in some way as well, which helped them solve the problem by removing apotheosis - I think it is resolved for that mod now as it did not seem to cause the same problem for me. (and despite having removed Apotheosis, this mod still caused the error)

The referenced issue about improper use of tags is here: https://github.com/vectorwing/FarmersDelight/issues/106
