### ISSUE TITLE
[1.15.2] Mod not loading correctly

### ISSUE THREAD

**Issue by vizthex123** [SilentChaos512/SuperMultiDrills#26]
## Versions

- **Super Multi-Drills**: 2.1.0+4
- **Silent Gear**:1.11.4+187
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.47
- **Modpack**: N/A , it's one I'm working on
- **Optifine Installed**: No

## Expected Behavior
The mod loads and thus the game does too.

## Actual Behavior
I get an error on load stating the mod didn't load correctly.

## Links/Images
Game log: 
[latest.log](https://github.com/SilentChaos512/SuperMultiDrills/files/5897687/latest.log)

## Steps to Reproduce the Problem

1. Install the mod
2. Load the game
3. See the screen

It may be an issue with another mod, but I'm not sure. Seems to just be contained to this one.

**Comment by SilverScreamBr** [comment]
Same issue here.

Probaly cause is Immersive Engineering Arc Furnace's recycling recipes

https://drive.google.com/file/d/1nbqXCaf0uz4DbS0bP1In8VSb_exFZXk0/view?usp=sharing

**Comment by SilentChaos512** [comment]
@SilverScreamBr Yikes, use a paste site! And paste a full crash report so I can at least tell what version you're on.

(edit) Wait, that's completely unrelated. Did you mean to comment on #25?

**Comment by SilentChaos512** [comment]
This issue looks like a mismatch between version of Silent Gear and Super Multi-Drills.
