### ISSUE TITLE
[1.16.5] Datapack Missing

### ISSUE THREAD

**Issue by Graffitoz** [SilentChaos512/SuperMultiDrills#27]
## Versions

- **Super Multi-Drills**: 2.2.3
- **Silent Gear**: 2.6.27
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.31
- **Modpack**: N/A
- **Optifine Installed**: Yes

## Expected Behavior

Be able to create a new world.

## Actual Behavior

"Errors in currently selected datapacks prevent the world from loading" whenever trying to create a new world with the mod present

## Links/Images

- Log: https://pastebin.com/rknvGJ4V (can't paste the full log due to pastebin limitations, hope this helps with something)

## Steps to Reproduce the Problem

1. Install the mod
2. Open the game
3. Try to create a new world

**Comment by najlitarvan** [comment]
are you running a datapack?

**Comment by Graffitoz** [comment]
> are you running a datapack?

Nope, idk how to make one.

**Comment by SilentChaos512** [comment]
Seems that Farmers Delight is causing some code that assumes parts are loaded to run before they are. But the issue is definitely on my end. Easy fix at least.
