### ISSUE TITLE
upgrades

### ISSUE THREAD

**Issue by fede9779** [SilentChaos512/SuperMultiDrills#29]
since i saw the texture in the file i wanted to know if you will add them in the future (area mining upgrade and others) (minecraft 1.16 / 1.17)

**Comment by SilentChaos512** [comment]
Those were in older versions of the mod and I'm not sure they will be coming back. Maybe area miner should.

**Comment by fede9779** [comment]
Since you integrated it with silent gear you can use the area upgrade for the hammer and excavator on the drill
