### ISSUE TITLE
Efficiency upgrade bug?

### ISSUE THREAD

**Issue by M4thG33k** [SilentChaos512/SuperMultiDrills#4]
Applying an efficiency upgrade to a drill seems to increase the cost of operation but not increase the mining speed (at least it's not affecting the tooltip). The current drill setup is: supercharged sapphire head, green chassis, performance motor, and large battery.

**Comment by SilentChaos512** [comment]
The tooltip shows the base speed, before the game does its funky Efficiency enchantment math. The enchantment does seem to work (tried it on dirt). I'll update the tooltip to make it a bit more clear.
