### ISSUE TITLE
Incorrect behavior when upgrade a (partially) charged drill battery + can't disable Mek recipes (can disable drill heads though).

### ISSUE THREAD

**Issue by BlazingGamer** [SilentChaos512/SuperMultiDrills#5]
![2016-03-20_22 17 40](https://cloud.githubusercontent.com/assets/13196222/13921693/36279b28-ef8a-11e5-8271-879b62c9e6ba.png)

**Comment by BlazingGamer** [comment]
![2016-03-21_17 30 09](https://cloud.githubusercontent.com/assets/13196222/13921827/de93bba2-ef8a-11e5-8bed-658a44b9da12.png)
The Mek recipes are disabled in config.

**Comment by SilentChaos512** [comment]
Fixing batteries losing charge when upgrading is a bit too much work for me right now (it's harder than you might think). But I can fix the recipe configs.
