### ISSUE TITLE
[REQUEST] Allow disassembly of drill

### ISSUE THREAD

**Issue by novasolarius** [SilentChaos512/SuperMultiDrills#6]
Yes, I know I can simply replace the parts. The thing is, not everybody makes two batteries, which makes upgrading them a pain.

**Comment by SilentChaos512** [comment]
Alright, I'll add something like a disassembly kit item when I have some time to spare.

**Comment by novasolarius** [comment]
Thank you very much.

**Comment by novasolarius** [comment]
:D
